"""ReportLab clinical report generation.

ReportLab, deliberately - WeasyPrint needs pango/cairo system libraries in
Docker and costs 30 minutes nobody has during a 24-hour build.
"""

from __future__ import annotations

from io import BytesIO
from typing import Any, Sequence

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

BRAND = colors.HexColor("#0F766E")
BAND_COLOR = {
    "LOW": colors.HexColor("#10B981"),
    "MEDIUM": colors.HexColor("#F59E0B"),
    "HIGH": colors.HexColor("#EF4444"),
}
BORDER = colors.HexColor("#E2E8F0")
SUBTLE = colors.HexColor("#F1F5F9")
MUTED = colors.HexColor("#64748B")

DISCLAIMER = (
    "<i>This report is clinical decision support generated by a statistical "
    "model. It is not a medical diagnosis. Final clinical judgement rests with "
    "the treating physician. The underlying model was trained on a public "
    "synthetic dataset; see the model card for limitations.</i>"
)


def _disclaimer_style(ss: Any) -> ParagraphStyle:
    return ParagraphStyle("d", parent=ss["Normal"], fontSize=8, textColor=MUTED)


def build_prediction_report(
    pred: Any,
    patient: Any,
    explanation: Any,
    recommendations: Sequence[dict[str, Any]],
) -> BytesIO:
    """Single-prediction clinical report."""
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=18 * mm, bottomMargin=18 * mm)
    ss = getSampleStyleSheet()
    h1 = ParagraphStyle("h1", parent=ss["Title"], textColor=BRAND, fontSize=18)
    story: list[Any] = [
        Paragraph("ReAdmitIQ - Readmission Risk Report", h1),
        Spacer(1, 8),
    ]
    story.append(
        Table(
            [
                ["Patient", patient.full_name, "MRN", patient.mrn],
                [
                    "Age / Gender",
                    f"{patient.age} / {patient.gender}",
                    "Condition",
                    patient.primary_condition,
                ],
                [
                    "Model",
                    pred.model_version,
                    "Generated",
                    pred.created_at.strftime("%d %b %Y %H:%M")
                    if pred.created_at
                    else "-",
                ],
            ],
            colWidths=[28 * mm, 55 * mm, 28 * mm, 55 * mm],
            style=TableStyle(
                [
                    ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
                    ("BACKGROUND", (0, 0), (0, -1), SUBTLE),
                    ("BACKGROUND", (2, 0), (2, -1), SUBTLE),
                    ("FONTSIZE", (0, 0), (-1, -1), 9),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ]
            ),
        )
    )
    band_color = BAND_COLOR.get(pred.risk_band, MUTED)
    story += [
        Spacer(1, 12),
        Paragraph(f"<b>Risk score: {pred.risk_probability * 100:.0f}%</b>", ss["Heading2"]),
        Paragraph(
            f'<font color="{band_color.hexval()}"><b>{pred.risk_band} RISK</b></font> '
            f"(decision threshold {pred.decision_threshold})",
            ss["Normal"],
        ),
        Spacer(1, 10),
        Paragraph("Clinical interpretation", ss["Heading3"]),
        Paragraph(explanation.narrative, ss["Normal"]),
        Spacer(1, 10),
        Paragraph("Contributing factors", ss["Heading3"]),
    ]
    rows = [["Factor", "Contribution", "Direction"]] + [
        [d["display"], f'{d["contribution"]:+.3f}', str(d["direction"]).title()]
        for d in (explanation.top_drivers or [])[:6]
    ]
    story.append(
        Table(
            rows,
            colWidths=[85 * mm, 35 * mm, 35 * mm],
            style=TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), BRAND),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
                    ("FONTSIZE", (0, 0), (-1, -1), 9),
                ]
            ),
        )
    )
    story += [Spacer(1, 12), Paragraph("Recommended actions", ss["Heading3"])]
    for r in recommendations:
        story.append(
            Paragraph(
                f'<b>[{r["priority"]}] {r["title"]}</b> - {r["detail"]}', ss["Normal"]
            )
        )
        story.append(Spacer(1, 4))
    story += [Spacer(1, 14), Paragraph(DISCLAIMER, _disclaimer_style(ss))]
    doc.build(story)
    buf.seek(0)
    return buf


def build_patient_report(
    patient: Any,
    admissions: Sequence[Any],
    predictions: Sequence[Any],
) -> BytesIO:
    """Longitudinal patient summary: admission history plus risk trajectory."""
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=18 * mm, bottomMargin=18 * mm)
    ss = getSampleStyleSheet()
    h1 = ParagraphStyle("h1", parent=ss["Title"], textColor=BRAND, fontSize=18)
    story: list[Any] = [
        Paragraph("ReAdmitIQ - Patient Summary", h1),
        Spacer(1, 8),
        Table(
            [
                ["Patient", patient.full_name, "MRN", patient.mrn],
                [
                    "Age / Gender",
                    f"{patient.age} / {patient.gender}",
                    "Condition",
                    patient.primary_condition,
                ],
                [
                    "Blood type",
                    patient.blood_type or "-",
                    "Insurer",
                    patient.insurance_provider or "-",
                ],
            ],
            colWidths=[28 * mm, 55 * mm, 28 * mm, 55 * mm],
            style=TableStyle(
                [
                    ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
                    ("BACKGROUND", (0, 0), (0, -1), SUBTLE),
                    ("BACKGROUND", (2, 0), (2, -1), SUBTLE),
                    ("FONTSIZE", (0, 0), (-1, -1), 9),
                ]
            ),
        ),
        Spacer(1, 12),
        Paragraph("Admission history", ss["Heading3"]),
    ]
    admission_rows = [["Admitted", "Discharged", "LOS", "Type", "Tests", "Follow-up"]] + [
        [
            a.admission_date.strftime("%d %b %Y"),
            a.discharge_date.strftime("%d %b %Y") if a.discharge_date else "-",
            str(a.length_of_stay),
            a.admission_type,
            a.test_result or "-",
            "Yes" if a.followup_scheduled else "No",
        ]
        for a in admissions
    ]
    story.append(
        Table(
            admission_rows,
            colWidths=[28 * mm, 28 * mm, 14 * mm, 26 * mm, 28 * mm, 26 * mm],
            style=TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), BRAND),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                ]
            ),
        )
    )
    story += [Spacer(1, 12), Paragraph("Risk trajectory", ss["Heading3"])]
    prediction_rows = [["Generated", "Risk", "Band", "Model"]] + [
        [
            p.created_at.strftime("%d %b %Y %H:%M") if p.created_at else "-",
            f"{p.risk_probability * 100:.0f}%",
            p.risk_band,
            p.model_version,
        ]
        for p in predictions
    ]
    story.append(
        Table(
            prediction_rows,
            colWidths=[45 * mm, 25 * mm, 30 * mm, 50 * mm],
            style=TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), BRAND),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                ]
            ),
        )
    )
    story += [Spacer(1, 14), Paragraph(DISCLAIMER, _disclaimer_style(ss))]
    doc.build(story)
    buf.seek(0)
    return buf
